version: '3'

services:
  postgres:
    image: 'postgres:9.6'
    container_name: 'bs-postgres'
    environment:
      - 'POSTGRES_PASSWORD=pixi3'
      - 'POSTGRES_USER=battleship'
      - 'POSTGRES_DB=battleship'
    ports:
      - '5432:5432'